# ========================================================
# Modernisation from previous version based on
# https://medium.com/swlh/dockerizing-a-react-application-with-docker-and-nginx-19e88ef8e99a
### STAGE 1: coping ###
FROM node:alpine
# FROM node:17.3.0-buster-slim as coping

# RUN mkdir /usr/src/app
WORKDIR /app


ENV PATH /app/node_modules/.bin:$PATH
# ENV NODE_OPTIONS=--openssl-legacy-provider

COPY package.json /app
COPY yarn.lock /app
COPY .bashrc /app
RUN cat .bashrc >> /root/.bashrc

RUN yarn

EXPOSE 80 443

CMD [ "yarn", "start:docker" ]

# =======================================>
# d build  --target coping -t front_coping .
# d run -it --name .... image /bin/bash
# d run --rm -it -p 8080:80 front_production
# It works.
