# FROM node:alpine
FROM node:16.14.2-buster-slim
# RUN mkdir /usr/src/app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
# ENV NODE_OPTIONS=--openssl-legacy-provider
COPY . /app
# COPY yarn.lock /app
# COPY .bashrc /app
# RUN cat .bashrc >> /root/.bashrc
RUN yarn
EXPOSE 3000
CMD [ "yarn", "start" ]
# =======================================>
# d build  --target coping -t front_coping .
# d run -it --name .... image /bin/bash
# d run --rm -it -p 8080:80 front_production
# It works.
