# ========================================================
# Modernisation from previous version based on
# https://medium.com/swlh/dockerizing-a-react-application-with-docker-and-nginx-19e88ef8e99a
### STAGE 1: coping ###
FROM node:alpine as build
# FROM node:17.3.0-buster-slim as coping

# RUN mkdir /usr/src/app
WORKDIR /app


# ENV NODE_OPTIONS=--openssl-legacy-provider

COPY . /app
ENV PATH /app/node_modules/.bin:$PATH
# COPY yarn.lock /app
# COPY .bashrc /app
RUN cat .bashrc >> /root/.bashrc

RUN yarn

RUN yarn build

CMD [ "yarn", "start" ]

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d
# EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]
# =======================================>
# d build  --target coping -t front_coping .
# d run -it --name .... image /bin/bash
# d run --rm -it -p 8080:80 front_production
# It works.
