version: '3.9'
# project_name: deployment

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: nginx:dev
    container_name: nginx_dev
    restart: unless-stopped
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ~/code/docker-logs/nginx/:/var/log/nginx/
    #   - nginxdata:/etc/ssl/private
    networks:
      - backend
      - frontend
    depends_on:
      - frontend
      - backend


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: frontend:dev
    container_name: frontend_dev
    restart: unless-stopped
    ports:
      - 3000:3000
      # - 443:443
    volumes:
      # - frontenddata:/etc/ssl/private
      # - ./frontend:/home/app
      - ./frontend:/app
      # - /app/node_modules
      # - nginxdata:/etc/nginx
      # - nginxlogs:/var/log/nginx
      # - /var/log/serverlogs/:/var/log/nginx
    depends_on:
      # - backend_serv
      - backend
    networks:
      - frontend


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: backend:dev
    container_name: backend_dev
    restart: unless-stopped

    networks:
      - backend
      - frontend

    expose:
      - 9090
    ports:
      - '9090:9090'

    # tty: true

    environment:
      APP_ENV: 'dev'
      APP_DEBUG: 'True'

      JWT_SECRET_KEY: 'very_secret_key'

      DATABASE_USER: 'coffee'
      DATABASE_PASSWORD: 'iij0*(*(*())^%^G'
      DATABASE_HOST: mysqldb
      DATABASE_NAME: 'market_coffee'

      MAIL_SERVER: 'smtp-relay.sendinblue.com'
      MAIL_PORT: 587
      MAIL_USERNAME: 'sa6702@gmail.com'
      MAIL_PASSWORD: 'xsmtpsib-6c8e1daad205cffaa2feba0c413cf4eba1e7fe5d9f661177d0a7249fc70b578b-XLPJgY0zh8aStfVj'
      MAIL_USE_TLS: True
      MAIL_USE_SSL: false
      # MAIL_DEFAULT_SENDER: ('TestSender', MAIL_USERNAME)
      # MAIL_SUPPRESS_SEND: True


    volumes:
      - ./backend:/backend

    depends_on:
      - mysqldb


  mysqldb:
    # build:
    #   context: ./mysql
    #   dockerfile: Dockerfile.dev
    # image: mysql:dev
    # container_name: mysql_dev
    # image: mysql:8.0.27
    image: mysql/mysql-server:8.0
    # image: mysql/mysql-server:latest
    container_name: mysqldb_dev
    hostname: mysqldb
    # command: '--authentication_policy=mysql_native_password'
    command: ["mysqld", "--general-log=1", "--general-log-file=/var/lib/mysql/log/general-log.log"]
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'ljoii98*_)(98767HG'
      MYSQL_DATABASE: market_coffee
      MYSQL_USER: coffee
      MYSQL_PASSWORD: 'iij0*(*(*())^%^G'

    volumes:
      - ~/code/docker-logs/mysql/:/var/lib/mysql/log/
      - 220415-market-caffee_mysqldata:/var/lib/mysql

    networks:
      - backend

    expose:
      - 3306
      - 33060
    # ports:
    #   - '3306:3306'


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  220415-market-caffee_mysqldata:
    external: true
    # driver: local
  # backenddata:
  #   driver: local
  # nginxdata:
  #   driver: local
  # nginxlogs:
  #   driver: local
  frontenddata:
    driver: local