FROM nginx:1.23.3 AS nano_installed

RUN apt update
RUN apt install -y nano
# d build --rm -f Dockerfile.dev --target nano_installed -t nginx:pre .
# --------------------------------------

FROM nginx:pre AS nginx_final
RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf
# Copy custom nginx config
COPY ./app.conf /etc/nginx/conf.d
COPY ./nginx.conf /etc/nginx

# COPY conf.d/app.conf /etc/nginx/conf.d/app.conf

# COPY ./Client/dist /usr/share/nginx/html

# EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]

# command to build image:
# d build --rm -f Dockerfile.dev --target nginx_final -t nginx:dev .