"""adding numbers in content for sorting  in paragraphs and controls.

Revision ID: 0072dac8d72c
Revises: 3917b155f0df
Create Date: 2021-04-12 10:01:52.056297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0072dac8d72c'
down_revision = '3917b155f0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'no')
    # ### end Alembic commands ###
