"""Initial migration.

Revision ID: 1f1da425ed5e
Revises:
Create Date: 2021-04-05 07:28:08.966077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1da425ed5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_kinds',
    sa.Column('id_kind', sa.String(length=64), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id_kind')
    )
    op.create_table('locales_global',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('remarks', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('remarks', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('views',
    sa.Column('id_view', sa.String(length=64), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id_view')
    )
    op.create_table('components',
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.Column('kind_id', sa.String(length=64), nullable=False),
    sa.Column('locale_id', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.Column('details', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['kind_id'], ['component_kinds.id_kind'], ),
    sa.ForeignKeyConstraint(['locale_id'], ['locales_global.id'], ),
    sa.PrimaryKeyConstraint('identity', 'kind_id', 'locale_id')
    )
    op.create_table('contents',
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.Column('view_id', sa.String(length=64), nullable=False),
    sa.Column('locale_id', sa.String(length=16), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['locale_id'], ['locales_global.id'], ),
    sa.ForeignKeyConstraint(['view_id'], ['views.id_view'], ),
    sa.PrimaryKeyConstraint('identity', 'view_id', 'locale_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('accessed', sa.DateTime(), nullable=True),
    sa.Column('user_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.String(length=24), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('locale_id', sa.String(length=16), nullable=False),
    sa.Column('time_zone', sa.SmallInteger(), nullable=False),
    sa.Column('remarks', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['locale_id'], ['locales_global.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('confirmations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmations')
    op.drop_table('users')
    op.drop_table('contents')
    op.drop_table('components')
    op.drop_table('views')
    op.drop_table('roles')
    op.drop_table('locales_global')
    op.drop_table('component_kinds')
    # ### end Alembic commands ###
