/**
 * Those constants used as menu keys
 */
export const ELEMENT_EDIT = 'ELEMENT_EDIT'
export const ELEMENT_SAVE = 'ELEMENT_SAVE'
export const ELEMENT_EDIT_SAVE = 'ELEMENT_EDIT_SAVE'
export const ELEMENT_EDIT_CANCEL = 'ELEMENT_EDIT_CANCEL'
export const ELEMENT_ADD_ABOVE = 'ELEMENT_ADD_ABOVE'
export const ELEMENT_ADD_BELOW = 'ELEMENT_ADD_BELOW'
export const ELEMENT_DELETE = 'ELEMENT_DELETE'
export const UPPER_ELEMENT_HANDLE = 'UPPER_ELEMENT_HANDLE'

export const UPPER_ELEMENT_ADD_ABOVE = 'UPPER_ELEMENT_ADD_ABOVE'
export const UPPER_ELEMENT_ADD_BELOW = 'UPPER_ELEMENT_ADD_BELOW'
export const UPPER_ELEMENT_DELETE = 'UPPER_ELEMENT_DELETE'
